language: objective-c
osx_image: xcode611
before_install:
  - gem install xcpretty
script:  xcodebuild -workspace TestsAndSample/Sample.xcworkspace -scheme Tests -sdk iphonesimulator8.1 test | xcpretty -c
